import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
        <head>
            <meta charSet="UTF-8" />
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1.0"
            />
            <title>To-Do List</title>
        </head>
        <body suppressHydrationWarning={true}>
            <div className="min-h-screen h-screen overflow-hidden dark:bg-boxdark-2 dark:text-bodydark">
                {children}
            </div>
        </body>
    </html>
);
}
